### PR TITLE
PutRecords to submit at most 500 records per call

### LINKED ISSUE #24: PutRecords calls are not split into batches of 500
The max limit of records for the `PutRecords` API is 500 (https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html). If a event is received with more than this we currently fail to process them as we try to put them into a single batch.

### PR DESCRIPTION
**Pull request by Mullefa**
## What does this change?

Ensure that no more than 500 records are submitted in a PutRecords request. See in-line comments or #24 for more context.

Resolves #24.

### CODE REVIEW

File: src/shipLogEntries.ts [hunk 1]
```diff
@@ -180,5 +181,5 @@ export async function shipLogEntries(event: CloudWatchLogsEvent, context: Contex
     });
     console.log(`Sending ${structuredLogs.length} events from ${logGroup} to ${kinesisStreamName} (with role: ${kinesisStreamRole})`);
     
-    await putKinesisRecords(kinesis, kinesisStreamName, structuredLogs);
+    return await putKinesisRecords(kinesis, kinesisStreamName, structuredLogs);
```
Comment (Mullefa) [inline src/shipLogEntries.ts:184]: The [invocation retries documentation](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html) states that common function errors are _"Your function's code throws an exception or returns an error object"_. Whilst I couldn't find an explicit definition of the _"error object"_ I'm presuming it should have fields `errorType` and `errorMessage` [e.g.](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-exceptions.html)

In particular, it seems that if there are instances of  `FailedRecordCount > 0` in the [`PutRecordsOutput[]`](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html), the lambda won't consider this as an error.

Presuming this is correct (?), should this be resolved by e.g. iterating through the `PutRecordsOutput[]` and raising an exception if `FailedRecordCount > 0` ?

Comment (sihil) [reply src/shipLogEntries.ts:184]: Interesting and probably.

At the very least we should log a line saying how many records we had failed to put, but given that this logging doing end up anywhere helpful...

Thinking about it we could directly ship to the ELK stream from this function so we could ship an ERROR level log entry from this function if it fails.

Ultimately though this is a question of how we are informed of issues.

File: src/kinesis.ts [hunk 2]
```diff
@@ -1,15 +1,25 @@
...
         }
     });
-    await kinesis.putRecords({
-        Records: records,
+
+    // Batch records since each put record request supports at most 500 records
+    // https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html
+    const batchRecords: PutRecordsRequestEntry[][] = [];
+    while (records.length > 0) {
+        batchRecords.push(records.splice(0, 500));
```
Comment (sihil) [inline src/kinesis.ts:16]: `splice` makes me a little sad as it's not pure but 🤷‍♂️

Comment (Mullefa) [reply src/kinesis.ts:16]: yeah, I was surprised when I checked that there wasn't a consensus answer on how to batch an array. The other approach in answer to [this](https://stackoverflow.com/questions/7273668/how-to-split-a-long-array-into-smaller-arrays-with-javascript) question doesn't mutate the array (at the cost of slightly more complicated code). Not sure if it's preferable 🤷‍♂️

Comment (sihil) [reply src/kinesis.ts:16]: I think it's OK as is. It's an array created inside the function so it's encapsulated.

File: src/shipLogEntries.ts (hunk 1 above)
Comment (sihil) [reply src/shipLogEntries.ts:184]: Thinking more, given the current mechanisms we have in place, if there are failures we should log stats and then throw. I suspect Error object is anything that extends Error so returning rather than throwing an exception?

Comment (Mullefa) [reply src/shipLogEntries.ts:184]: > Ultimately though this is a question of how we are informed of issues.

Yes - good point. Ok, I won't look to solve this in the current PR, but will create an issue. I guess as part of solving this, we could also think about the case when the Promise is rejected. In that case it's reported as a failed invocation (good!) but perhaps notification needs to be automated - alarms etc.

Comment (Mullefa) [reply src/shipLogEntries.ts:184]: > Thinking more, given the current mechanisms we have in place, if there are failures we should log stats and then throw. I suspect Error object is anything that extends Error so returning rather than throwing an exception?

Yes, this seems like a good starting point. After this change then at least alarms can be configured per account if the respective team deems it appropriate.

Ok, to follow this up in a separate PR ?

**Comment by Mullefa** [comment]
@sihil (or alternatively @akash1810 if you feel comfortable reviewing this), could I please get a final review/approve. Thanks!
